app = "expendition"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "80"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
